# Generated by Django 5.2.5 on 2025-09-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaejercicio',
            name='descanso_segundos',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='entradaejercicio',
            name='rir',
            field=models.PositiveIntegerField(default=1, help_text='Repeticiones en reserva'),
        ),
        migrations.AddField(
            model_name='entradaejercicio',
            name='rpe',
            field=models.PositiveIntegerField(default=9, help_text='Esfuerzo percibido (1-10)'),
        ),
    ]
