# Generated by Django 5.2.6 on 2025-09-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0002_entradaejercicio_descanso_segundos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaejercicio',
            name='notas',
            field=models.TextField(blank=True),
        ),
    ]
