# Generated by Django 5.2.6 on 2025-11-07 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_cliente_usuario_alter_cliente_entrenadores"),
        ("ejercicios", "0004_ejercicio_visibilidad"),
        ("rutinas", "0003_entradaejercicio_notas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rutina",
            name="ejercicios",
            field=models.ManyToManyField(
                related_name="rutinas", to="ejercicios.ejercicio"
            ),
        ),
        migrations.AddField(
            model_name="rutina",
            name="entrenador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rutinas_creadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rutina",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rutinas",
                to="clientes.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="rutina",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
