# Generated by Django 5.2.6 on 2025-11-08 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0005_alter_cliente_entrenadores"),
        ("ejercicios", "0004_ejercicio_visibilidad"),
        ("rutinas", "0004_rutina_ejercicios_rutina_entrenador_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="rutina",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rutinas_asignadas",
                to="clientes.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="rutina",
            name="ejercicios",
            field=models.ManyToManyField(blank=True, to="ejercicios.ejercicio"),
        ),
        migrations.AlterField(
            model_name="rutina",
            name="entrenador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rutinas_asignadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
