# Generated by Django 5.2.5 on 2025-09-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('grupo_muscular', models.CharField(max_length=100)),
                ('descanso_segundos', models.PositiveIntegerField(default=60)),
                ('rir', models.PositiveIntegerField(help_text='Repeticiones en reserva')),
                ('rpe', models.PositiveIntegerField(help_text='Esfuerzo percibido (1-10)')),
            ],
        ),
    ]
