# Generated by Django 5.2.5 on 2025-09-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='descanso_segundos',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='rir',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='rpe',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='variante',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
