# Generated by Django 5.2.6 on 2025-10-31 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ejercicios", "0002_remove_ejercicio_descanso_segundos_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ejercicio",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ejercicios",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
