# Generated by Django 5.2.6 on 2025-10-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ejercicios", "0003_ejercicio_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="ejercicio",
            name="visibilidad",
            field=models.CharField(
                choices=[("privado", "Privado"), ("global", "Global")],
                default="privado",
                max_length=10,
            ),
        ),
    ]
