# Generated by Django 5.2.5 on 2025-09-29 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cintura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pecho_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('brazo_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pierna_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
