# Generated by Django 5.2.6 on 2025-09-30 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('ejercicios', '0002_remove_ejercicio_descanso_segundos_and_more'),
        ('progreso', '0001_initial'),
        ('rutinas', '0003_entradaejercicio_notas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('series', models.PositiveIntegerField(default=1)),
                ('repeticiones', models.PositiveIntegerField()),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_ejercicios', to='clientes.cliente')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejercicios.ejercicio')),
                ('rutina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progresos_ejercicios', to='rutinas.rutina')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
