# Generated by Django 5.2.6 on 2025-10-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progreso", "0002_progresoejercicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="progresoejercicio",
            name="rir",
            field=models.PositiveIntegerField(
                blank=True, help_text="Repeticiones en reserva (0-5 aprox)", null=True
            ),
        ),
        migrations.AddField(
            model_name="progresoejercicio",
            name="rpe",
            field=models.PositiveIntegerField(
                blank=True, help_text="Esfuerzo percibido (1-10)", null=True
            ),
        ),
    ]
