# Generated by Django 5.2.6 on 2025-11-01 22:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_initial"),
        ("ejercicios", "0004_ejercicio_visibilidad"),
        ("progreso", "0003_progresoejercicio_rir_progresoejercicio_rpe"),
    ]

    operations = [
        migrations.CreateModel(
            name="RutinaDiaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.localdate)),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rutinas_diarias",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
                "unique_together": {("cliente", "fecha")},
            },
        ),
        migrations.CreateModel(
            name="SerieDiaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series", models.PositiveIntegerField(default=1)),
                ("repeticiones", models.PositiveIntegerField()),
                (
                    "peso",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "ejercicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ejercicios.ejercicio",
                    ),
                ),
                (
                    "rutina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to="progreso.rutinadiaria",
                    ),
                ),
            ],
        ),
    ]
