# Generated by Django 5.2.6 on 2025-11-01 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progreso", "0004_rutinadiaria_seriediaria"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seriediaria",
            name="rutina",
        ),
        migrations.RemoveField(
            model_name="seriediaria",
            name="ejercicio",
        ),
        migrations.DeleteModel(
            name="RutinaDiaria",
        ),
        migrations.DeleteModel(
            name="SerieDiaria",
        ),
    ]
