# Generated by Django 5.2.6 on 2025-11-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progreso", "0005_remove_seriediaria_rutina_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="progresoejercicio",
            name="peso_maximo",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="progresoejercicio",
            name="repeticiones_maximas",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
