# Generated by Django 5.2.6 on 2025-11-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progreso", "0006_progresoejercicio_peso_maximo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="progresoejercicio",
            name="peso_maximo",
        ),
        migrations.RemoveField(
            model_name="progresoejercicio",
            name="repeticiones_maximas",
        ),
    ]
