# Generated by Django 5.2.6 on 2025-11-09 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ejercicios", "0004_ejercicio_visibilidad"),
        ("progreso", "0007_remove_progresoejercicio_peso_maximo_and_more"),
        ("rutinas", "0005_alter_rutina_cliente_alter_rutina_ejercicios_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="progreso",
            options={},
        ),
        migrations.RenameField(
            model_name="progreso",
            old_name="notas",
            new_name="comentario_cliente",
        ),
        migrations.RemoveField(
            model_name="progreso",
            name="altura_cm",
        ),
        migrations.RemoveField(
            model_name="progreso",
            name="brazo_cm",
        ),
        migrations.RemoveField(
            model_name="progreso",
            name="cintura_cm",
        ),
        migrations.RemoveField(
            model_name="progreso",
            name="pecho_cm",
        ),
        migrations.RemoveField(
            model_name="progreso",
            name="pierna_cm",
        ),
        migrations.AddField(
            model_name="progreso",
            name="comentario_entrenador",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="progreso",
            name="descanso_seg",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="progreso",
            name="ejercicio",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="ejercicios.ejercicio",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="progreso",
            name="repeticiones",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="progreso",
            name="rir",
            field=models.PositiveIntegerField(
                blank=True, help_text="Repeticiones en reserva", null=True
            ),
        ),
        migrations.AddField(
            model_name="progreso",
            name="rutina",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progresos",
                to="rutinas.rutina",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="progreso",
            name="fecha",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="progreso",
            name="peso_kg",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
