# Generated by Django 5.2.6 on 2025-11-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progreso", "0008_alter_progreso_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="progreso",
            options={"ordering": ["-fecha"]},
        ),
        migrations.RenameField(
            model_name="progreso",
            old_name="comentario_cliente",
            new_name="notas",
        ),
        migrations.RemoveField(
            model_name="progreso",
            name="comentario_entrenador",
        ),
        migrations.RemoveField(
            model_name="progreso",
            name="descanso_seg",
        ),
        migrations.RemoveField(
            model_name="progreso",
            name="ejercicio",
        ),
        migrations.RemoveField(
            model_name="progreso",
            name="repeticiones",
        ),
        migrations.RemoveField(
            model_name="progreso",
            name="rir",
        ),
        migrations.RemoveField(
            model_name="progreso",
            name="rutina",
        ),
        migrations.AddField(
            model_name="progreso",
            name="altura_cm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="progreso",
            name="brazo_cm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="progreso",
            name="cintura_cm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="progreso",
            name="pecho_cm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="progreso",
            name="pierna_cm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="progreso",
            name="fecha",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="progreso",
            name="peso_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
