# Generated by Django 5.2.6 on 2025-11-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("entrenador", "Entrenador"),
                    ("cliente", "Cliente"),
                ],
                default="cliente",
                max_length=20,
            ),
        ),
    ]
