# Generated by Django 5.2.5 on 2025-09-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('altura_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('peso_kg', models.FloatField(blank=True, null=True)),
                ('lesiones', models.TextField(blank=True, help_text='Anotar lesiones o complicaciones')),
            ],
        ),
    ]
