# Generated by Django 5.2.5 on 2025-09-28 00:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='entrenadores',
            field=models.ManyToManyField(related_name='clientes', to=settings.AUTH_USER_MODEL),
        ),
    ]
