# Generated by Django 5.2.6 on 2025-11-08 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_cliente_usuario_alter_cliente_entrenadores"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="entrenadores",
            field=models.ManyToManyField(
                related_name="clientes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
